version: '3.5'

services:
  postgres:
    container_name: sb_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - /Users/e.bagryantseva/uni/SB/postgreSQL:/data/sb
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
       driver: bridge
